### PR TITLE
Exit on SIGINT after sending the last report if Optics is the only handler

### LINKED ISSUE #94: Optics agent seems to prevent Node to shutdown
Hello,

Since the latest version it seems that you intercept SIGINT without properly exiting 

https://github.com/apollographql/optics-agent-js/commit/864134711e3ebfeb816091e187c46e5517e2df9f#diff-224869730a5b5fad7d7aa8feb091db60R92

Not a big deal, but it prevent my server from exiting when I CTRL+C for example ;)

### PR DESCRIPTION
**Pull request by ide**
Node has a default SIGINT handler that exits but disables it when a custom handler is added. Optics adds a handler but didn't exit, which meant the process would hang indefinitely. This adds a handler in the SIGINT code path (not the "exit" event code path because only one run of the event loop executes and then Node exits) that checks if Optics is the only handler and if so, tells Node to exit.

Tested by launching Node with Optics and seeing that Ctrl+C now quickly terminates the process instead of seeing it hang.

Fixes #94

### CODE REVIEW

**Comment by martijnwalraven** [comment]
Thanks a lot for fixing this! Published as 1.1.5.

**Comment by ide** [comment]
@martijnwalraven It looks like this patch isn't in 1.1.5 installed from npm. Perhaps the `dist` directory still had the old code when publishing?

**Comment by martijnwalraven** [comment]
@ide Oops, sorry about that. I rebuilt `dist` manually and published as 1.1.6.

I've ran into this issue before, and it seems npm doesn't run `prepare` before a `publish` even though that's how I understand it is supposed to work. But maybe I'm missing something here. Do you have any insights on this?

**Comment by ide** [comment]
Could it be related to your version of npm? (I think `prepare` was implemented only in npm 4+)

**Comment by martijnwalraven** [comment]
Ah, that makes sense, I was running npm 3. Thanks!

**Pull request merged**
