### PR TITLE
add koaMiddleware

### PR DESCRIPTION
**Pull request by kesla**
Added middleware for koa@2.

Tested with our internal graphql-server.

### CODE REVIEW

**Comment by kesla** [comment]
Can I do something to get this merged?

**Comment by kesla** [comment]
I've signed the CLA

**Comment by cvburgess** [comment]
Not to add a "me too" but we started our trial, hooked up as much as we could and realized theres no official Koa support (even though the logo is on the site) - bummer. Hope this gets resolved and we can try Optics again.

**Comment by kesla** [comment]
@stubailo here's a 3rd one! 💃

**Comment by pcarrier** [comment]
Thanks! Merged by hand in `master` to include eslint fixes.

**Pull request closed without merging**
